name: Test

on: pull_request

jobs:
  build:
    strategy:
      matrix:
        os: [ macOS-latest, ubuntu-18.04, windows-latest ]
        job: [ build, test ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup JDK 11
        uses: actions/setup-java@v3.4.0
        with:
          distribution: 'zulu'
          java-version: 11
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          cache-disabled: true

      - name: Run MacOS Tests
        if: matrix.os == 'macOS-latest' && matrix.job == 'test'
        run: |
          ./gradlew check --stacktrace -PKMP_TARGETS=JVM,JS,IOS_ARM32,IOS_ARM64,IOS_X64,IOS_SIMULATOR_ARM64,MACOS_ARM64,MACOS_X64,TVOS_ARM64,TVOS_X64,TVOS_SIMULATOR_ARM64,WATCHOS_ARM32,WATCHOS_ARM64,WATCHOS_X64,WATCHOS_X86,WATCHOS_SIMULATOR_ARM64

      - name: Run Linux Tests
        if: matrix.os == 'ubuntu-18.04' && matrix.job == 'test'
        run: |
          ./gradlew check --stacktrace -PKMP_TARGETS=ANDROID,JVM,JS,LINUX_ARM32HFP,LINUX_ARM64,LINUX_MIPS32,LINUX_MIPSEL32,LINUX_X64

      - name: Run Windows Tests
        if: matrix.os == 'windows-latest' && matrix.job == 'test'
        run: |
          ./gradlew check --stacktrace -PKMP_TARGETS=JVM,JS,MINGW_X64,MINGW_X86

      - name: Build Kotlin Android Sample
        if: matrix.os == 'macOs-latest' && matrix.job == 'build'
        with:
          arguments: build --stacktrace -PKMP_TARGETS=ANDROID,JVM
          build-root-directory: samples/kotlin/android
          cache-disabled: true

      - name: Build TornadoFx Sample
        if: matrix.os == 'macOS-latest' && matrix.job == 'build'
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build --stacktrace -PKMP_TARGETS=JVM
          build-root-directory: samples/kotlin/javafx
          cache-disabled: true

## TODO: Upload build reports

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Dkotlin.incremental=false -Dorg.gradle.jvmargs="-XX:+HeapDumpOnOutOfMemoryError -XX:MetaspaceSize=1g"
